"""FastAPI application factory.

Everything here is infrastructure wiring — middleware order, lifespan
startup/shutdown, exception handlers, router inclusion. No business
routes live in this file; see app/api/v1/router.py for how new endpoint
modules get added without touching this one.

Middleware order matters (Starlette applies them outermost-first as
listed): CORS and TrustedHost run first so a disallowed origin/host is
rejected before any app logic runs; RequestContextMiddleware runs early
so every subsequent middleware and handler has a request_id to log with;
SecurityHeadersMiddleware runs last so headers land on every response,
including ones generated by exception handlers.
"""

import asyncio
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

import structlog
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.trustedhost import TrustedHostMiddleware
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.middleware import SlowAPIMiddleware

from app.api.v1.router import api_router
from app.core.colors import CYAN, GREEN, colorize
from app.core.config import settings
from app.core.exceptions import register_exception_handlers
from app.core.logging import configure_logging
from app.core.middleware import RequestContextMiddleware, SecurityHeadersMiddleware
from app.core.rate_limit import limiter
from app.core.startup import run_startup_checks
from app.db.session import engine
from app.ws.connection_manager import manager
from app.ws.router import router as ws_router

configure_logging()
logger = structlog.get_logger(__name__)


@asynccontextmanager
async def lifespan(_app: FastAPI) -> AsyncIterator[None]:
    # Fail fast: refuse to accept traffic if Postgres/Redis/the queue
    # broker aren't reachable, rather than starting "successfully" and
    # failing confusingly on the first real request.
    await run_startup_checks()

    listener_task = asyncio.create_task(manager.start_listener())
    logger.info(colorize("websocket_manager_initialized", GREEN))

    logger.info(colorize("dart_backend_ready", GREEN), environment=settings.environment)
    try:
        yield
    finally:
        logger.info(colorize("shutdown_started", CYAN))
        listener_task.cancel()
        await asyncio.gather(listener_task, return_exceptions=True)
        await engine.dispose()
        logger.info(colorize("shutdown_complete", CYAN))


def create_app() -> FastAPI:
    app = FastAPI(
        title=settings.project_name,
        docs_url="/docs" if settings.docs_enabled else None,
        redoc_url="/redoc" if settings.docs_enabled else None,
        openapi_url="/openapi.json" if settings.docs_enabled else None,
        lifespan=lifespan,
    )

    # --- middleware (order matters — see module docstring) ---
    app.add_middleware(
        TrustedHostMiddleware,
        allowed_hosts=settings.allowed_hosts,
    )
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_credentials=True,
        allow_methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
        allow_headers=["Authorization", "Content-Type", "X-Request-ID"],
        expose_headers=["X-Total-Count", "Content-Disposition"],
    )
    app.add_middleware(RequestContextMiddleware)
    app.add_middleware(SecurityHeadersMiddleware)

    app.state.limiter = limiter
    # slowapi's own handler is typed narrower (RateLimitExceeded) than
    # Starlette's generic Exception-handler signature expects — this is
    # slowapi's documented registration pattern, not a real type error.
    app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)  # type: ignore[arg-type]
    app.add_middleware(SlowAPIMiddleware)

    register_exception_handlers(app)

    app.include_router(api_router, prefix=settings.api_v1_prefix)
    app.include_router(ws_router)

    return app


app = create_app()
